<?php
return array (
  'AF'=>array('name'=>'AFGHANISTAN','code'=>'93'),
  'AL'=>array('name'=>'ALBANIA','code'=>'355'),
  'DZ'=>array('name'=>'ALGERIA','code'=>'213'),
  'AS'=>array('name'=>'AMERICAN SAMOA','code'=>'1684'),
  'AD'=>array('name'=>'ANDORRA','code'=>'376'),
  'AO'=>array('name'=>'ANGOLA','code'=>'244'),
  'AI'=>array('name'=>'ANGUILLA','code'=>'1264'),
  'AQ'=>array('name'=>'ANTARCTICA','code'=>'672'),
  'AG'=>array('name'=>'ANTIGUA AND BARBUDA','code'=>'1268'),
  'AR'=>array('name'=>'ARGENTINA','code'=>'54'),
  'AM'=>array('name'=>'ARMENIA','code'=>'374'),
  'AW'=>array('name'=>'ARUBA','code'=>'297'),
  'AU'=>array('name'=>'AUSTRALIA','code'=>'61'),
  'AT'=>array('name'=>'AUSTRIA','code'=>'43'),
  'AZ'=>array('name'=>'AZERBAIJAN','code'=>'994'),
  'BS'=>array('name'=>'BAHAMAS','code'=>'1242'),
  'BH'=>array('name'=>'BAHRAIN','code'=>'973'),
  'BD'=>array('name'=>'BANGLADESH','code'=>'880'),
  'BB'=>array('name'=>'BARBADOS','code'=>'1246'),
  'BY'=>array('name'=>'BELARUS','code'=>'375'),
  'BE'=>array('name'=>'BELGIUM','code'=>'32'),
  'BZ'=>array('name'=>'BELIZE','code'=>'501'),
  'BJ'=>array('name'=>'BENIN','code'=>'229'),
  'BM'=>array('name'=>'BERMUDA','code'=>'1441'),
  'BT'=>array('name'=>'BHUTAN','code'=>'975'),
  'BO'=>array('name'=>'BOLIVIA','code'=>'591'),
  'BA'=>array('name'=>'BOSNIA AND HERZEGOVINA','code'=>'387'),
  'BW'=>array('name'=>'BOTSWANA','code'=>'267'),
  'BR'=>array('name'=>'BRAZIL','code'=>'55'),
  'BN'=>array('name'=>'BRUNEI DARUSSALAM','code'=>'673'),
  'BG'=>array('name'=>'BULGARIA','code'=>'359'),
  'BF'=>array('name'=>'BURKINA FASO','code'=>'226'),
  'BI'=>array('name'=>'BURUNDI','code'=>'257'),
  'CI'=>array('name'=>'COTE D\'IVOIRE','code'=>'225'),
  'CV'=>array('name'=>'CABO VERDE','code'=>'238'),
  'KH'=>array('name'=>'CAMBODIA','code'=>'855'),
  'CM'=>array('name'=>'CAMEROON','code'=>'237'),
  'CA'=>array('name'=>'CANADA','code'=>'1'),
  'KY'=>array('name'=>'CAYMAN ISLANDS','code'=>'1345'),
  'CF'=>array('name'=>'CENTRAL AFRICAN REPUBLIC','code'=>'236'),
  'TD'=>array('name'=>'CHAD','code'=>'235'),
  'CL'=>array('name'=>'CHILE','code'=>'56'),
  'CN'=>array('name'=>'CHINA','code'=>'86'),
  'CO'=>array('name'=>'COLOMBIA','code'=>'57'),
  'KM'=>array('name'=>'COMOROS','code'=>'269'),
  'CG'=>array('name'=>'CONGO','code'=>'242'),
  'CD'=>array('name'=>'THE DEMOCRATIC REPUBLIC OF THE CONGO','code'=>'243'),
  'CK'=>array('name'=>'COOK ISLANDS','code'=>'682'),
  'CR'=>array('name'=>'COSTA RICA','code'=>'506'),
  'HR'=>array('name'=>'CROATIA','code'=>'385'),
  'CU'=>array('name'=>'CUBA','code'=>'53'),
  'CY'=>array('name'=>'CYPRUS','code'=>'357'),
  'CZ'=>array('name'=>'CZECH REPUBLIC','code'=>'420'),
  'DK'=>array('name'=>'DENMARK','code'=>'45'),
  'DJ'=>array('name'=>'DJIBOUTI','code'=>'253'),
  'DM'=>array('name'=>'DOMINICA','code'=>'1767'),
  'DO'=>array('name'=>'DOMINICAN REPUBLIC','code'=>'1809'),
  'EC'=>array('name'=>'ECUADOR','code'=>'593'),
  'EG'=>array('name'=>'EGYPT','code'=>'20'),
  'SV'=>array('name'=>'EL SALVADOR','code'=>'503'),
  'GQ'=>array('name'=>'EQUATORIAL GUINEA','code'=>'240'),
  'ER'=>array('name'=>'ERITREA','code'=>'291'),
  'EE'=>array('name'=>'ESTONIA','code'=>'372'),
  'ET'=>array('name'=>'ETHIOPIA','code'=>'251'),
  'FO'=>array('name'=>'FAROE ISLANDS','code'=>'298'),
  'FJ'=>array('name'=>'FIJI','code'=>'679'),
  'FI'=>array('name'=>'FINLAND','code'=>'358'),
  'FR'=>array('name'=>'FRANCE','code'=>'33'),
  'PF'=>array('name'=>'FRENCH POLYNESIA','code'=>'689'),
  'GA'=>array('name'=>'GABON','code'=>'241'),
  'GM'=>array('name'=>'GAMBIA','code'=>'220'),
  'GE'=>array('name'=>'GEORGIA','code'=>'995'),
  'DE'=>array('name'=>'GERMANY','code'=>'49'),
  'GH'=>array('name'=>'GHANA','code'=>'233'),
  'GI'=>array('name'=>'GIBRALTAR','code'=>'350'),
  'GR'=>array('name'=>'GREECE','code'=>'30'),
  'GL'=>array('name'=>'GREENLAND','code'=>'299'),
  'GD'=>array('name'=>'GRENADA','code'=>'1473'),
  'GT'=>array('name'=>'GUATEMALA','code'=>'502'),
  'GN'=>array('name'=>'GUINEA','code'=>'224'),
  'GW'=>array('name'=>'GUINEA-BISSAU','code'=>'245'),
  'GU'=>array('name'=>'GUAM','code'=>'1671'),
  'GY'=>array('name'=>'GUYANA','code'=>'592'),
  'HT'=>array('name'=>'HAITI','code'=>'509'),
  'VA'=>array('name'=>'HOLY SEE (VATICAN CITY STATE)','code'=>'39'),
  'HN'=>array('name'=>'HONDURAS','code'=>'504'),
  'HK'=>array('name'=>'HONG KONG','code'=>'852'),
  'HU'=>array('name'=>'HUNGARY','code'=>'36'),
  'IS'=>array('name'=>'ICELAND','code'=>'354'),
  'IN'=>array('name'=>'INDIA','code'=>'91'),
  'ID'=>array('name'=>'INDONESIA','code'=>'62'),
  'IR'=>array('name'=>'IRAN','code'=>'98'),
  'IQ'=>array('name'=>'IRAQ','code'=>'964'),
  'IE'=>array('name'=>'IRELAND','code'=>'353'),
  'IL'=>array('name'=>'ISRAEL','code'=>'972'),
  'IT'=>array('name'=>'ITALY','code'=>'39'),
  'JM'=>array('name'=>'JAMAICA','code'=>'1876'),
  'JP'=>array('name'=>'JAPAN','code'=>'81'),
  'JO'=>array('name'=>'JORDAN','code'=>'962'),
  'KZ'=>array('name'=>'KAZAKSTAN','code'=>'7'),
  'KE'=>array('name'=>'KENYA','code'=>'254'),
  'KI'=>array('name'=>'KIRIBATI','code'=>'686'),
  'KP'=>array('name'=>'DEMOCRATIC PEOPLES REPUBLIC OF KOREA','code'=>'850'),
  'KR'=>array('name'=>'REPUBLIC OF KOREA','code'=>'82'),
  'XK'=>array('name'=>'KOSOVO','code'=>'381'),
  'KW'=>array('name'=>'KUWAIT','code'=>'965'),
  'KG'=>array('name'=>'KYRGYZSTAN','code'=>'996'),
  'LA'=>array('name'=>'PEOPLES DEMOCRATIC REPUBLIC LAO','code'=>'856'),
  'LV'=>array('name'=>'LATVIA','code'=>'371'),
  'LB'=>array('name'=>'LEBANON','code'=>'961'),
  'LS'=>array('name'=>'LESOTHO','code'=>'266'),
  'LR'=>array('name'=>'LIBERIA','code'=>'231'),
  'LY'=>array('name'=>'LIBYAN ARAB JAMAHIRIYA','code'=>'218'),
  'LI'=>array('name'=>'LIECHTENSTEIN','code'=>'423'),
  'LT'=>array('name'=>'LITHUANIA','code'=>'370'),
  'LU'=>array('name'=>'LUXEMBOURG','code'=>'352'),
  'MO'=>array('name'=>'MACAU','code'=>'853'),
  'MG'=>array('name'=>'MADAGASCAR','code'=>'261'),
  'MW'=>array('name'=>'MALAWI','code'=>'265'),
  'MY'=>array('name'=>'MALAYSIA','code'=>'60'),
  'MV'=>array('name'=>'MALDIVES','code'=>'960'),
  'ML'=>array('name'=>'MALI','code'=>'223'),
  'MT'=>array('name'=>'MALTA','code'=>'356'),
  'MH'=>array('name'=>'MARSHALL ISLANDS','code'=>'692'),
  'MR'=>array('name'=>'MAURITANIA','code'=>'222'),
  'MU'=>array('name'=>'MAURITIUS','code'=>'230'),
  'YT'=>array('name'=>'MAYOTTE','code'=>'262'),
  'MX'=>array('name'=>'MEXICO','code'=>'52'),
  'FM'=>array('name'=>'FEDERATED STATES OF MICRONESIA','code'=>'691'),
  'MD'=>array('name'=>'REPUBLIC OF MOLDOVA','code'=>'373'),
  'MC'=>array('name'=>'MONACO','code'=>'377'),
  'MN'=>array('name'=>'MONGOLIA','code'=>'976'),
  'ME'=>array('name'=>'MONTENEGRO','code'=>'382'),
  'MS'=>array('name'=>'MONTSERRAT','code'=>'1664'),
  'MA'=>array('name'=>'MOROCCO','code'=>'212'),
  'MZ'=>array('name'=>'MOZAMBIQUE','code'=>'258'),
  'MM'=>array('name'=>'MYANMAR','code'=>'95'),
  'NA'=>array('name'=>'NAMIBIA','code'=>'264'),
  'NR'=>array('name'=>'NAURU','code'=>'674'),
  'NP'=>array('name'=>'NEPAL','code'=>'977'),
  'NL'=>array('name'=>'NETHERLANDS','code'=>'31'),
  'AN'=>array('name'=>'NETHERLANDS ANTILLES','code'=>'599'),
  'NC'=>array('name'=>'NEW CALEDONIA','code'=>'687'),
  'NZ'=>array('name'=>'NEW ZEALAND','code'=>'64'),
  'NI'=>array('name'=>'NICARAGUA','code'=>'505'),
  'NE'=>array('name'=>'NIGER','code'=>'227'),
  'NG'=>array('name'=>'NIGERIA','code'=>'234'),
  'NU'=>array('name'=>'NIUE','code'=>'683'),
  'MK'=>array('name'=>'NORTH MACEDONIA','code'=>'389'),
  'MP'=>array('name'=>'NORTHERN MARIANA ISLANDS','code'=>'1670'),
  'NO'=>array('name'=>'NORWAY','code'=>'47'),
  'OM'=>array('name'=>'OMAN','code'=>'968'),
  'PK'=>array('name'=>'PAKISTAN','code'=>'92'),
  'PW'=>array('name'=>'PALAU','code'=>'680'),
  'PA'=>array('name'=>'PANAMA','code'=>'507'),
  'PG'=>array('name'=>'PAPUA NEW GUINEA','code'=>'675'),
  'PY'=>array('name'=>'PARAGUAY','code'=>'595'),
  'PE'=>array('name'=>'PERU','code'=>'51'),
  'PH'=>array('name'=>'PHILIPPINES','code'=>'63'),
  'PN'=>array('name'=>'PITCAIRN','code'=>'870'),
  'PL'=>array('name'=>'POLAND','code'=>'48'),
  'PT'=>array('name'=>'PORTUGAL','code'=>'351'),
  'PR'=>array('name'=>'PUERTO RICO','code'=>'1'),
  'QA'=>array('name'=>'QATAR','code'=>'974'),
  'RO'=>array('name'=>'ROMANIA','code'=>'40'),
  'RU'=>array('name'=>'RUSSIAN FEDERATION','code'=>'7'),
  'RW'=>array('name'=>'RWANDA','code'=>'250'),
  'BL'=>array('name'=>'SAINT BARTHELEMY','code'=>'590'),
  'SH'=>array('name'=>'SAINT HELENA','code'=>'290'),
  'KN'=>array('name'=>'SAINT KITTS AND NEVIS','code'=>'1869'),
  'LC'=>array('name'=>'SAINT LUCIA','code'=>'1758'),
  'MF'=>array('name'=>'SAINT MARTIN','code'=>'1599'),
  'PM'=>array('name'=>'SAINT PIERRE AND MIQUELON','code'=>'508'),
  'VC'=>array('name'=>'SAINT VINCENT AND THE GRENADINES','code'=>'1784'),
  'WS'=>array('name'=>'SAMOA','code'=>'685'),
  'SM'=>array('name'=>'SAN MARINO','code'=>'378'),
  'ST'=>array('name'=>'SAO TOME AND PRINCIPE','code'=>'239'),
  'SA'=>array('name'=>'SAUDI ARABIA','code'=>'966'),
  'SN'=>array('name'=>'SENEGAL','code'=>'221'),
  'RS'=>array('name'=>'SERBIA','code'=>'381'),
  'SC'=>array('name'=>'SEYCHELLES','code'=>'248'),
  'SL'=>array('name'=>'SIERRA LEONE','code'=>'232'),
  'SG'=>array('name'=>'SINGAPORE','code'=>'65'),
  'SK'=>array('name'=>'SLOVAKIA','code'=>'421'),
  'SI'=>array('name'=>'SLOVENIA','code'=>'386'),
  'SB'=>array('name'=>'SOLOMON ISLANDS','code'=>'677'),
  'SO'=>array('name'=>'SOMALIA','code'=>'252'),
  'ZA'=>array('name'=>'SOUTH AFRICA','code'=>'27'),
  'SS'=>array('name'=>'SOUTH SUDAN','code'=>'211'),
  'ES'=>array('name'=>'SPAIN','code'=>'34'),
  'LK'=>array('name'=>'SRI LANKA','code'=>'94'),
  'SD'=>array('name'=>'SUDAN','code'=>'249'),
  'SR'=>array('name'=>'SURINAME','code'=>'597'),
  'SZ'=>array('name'=>'SWAZILAND','code'=>'268'),
  'SE'=>array('name'=>'SWEDEN','code'=>'46'),
  'CH'=>array('name'=>'SWITZERLAND','code'=>'41'),
  'SY'=>array('name'=>'SYRIAN ARAB REPUBLIC','code'=>'963'),
  'TJ'=>array('name'=>'TAJIKISTAN','code'=>'992'),
  'TW'=>array('name'=>'TAIWAN','code'=>'886'),
  'TZ'=>array('name'=>'UNITED REPUBLIC OF TANZANIA','code'=>'255'),
  'TH'=>array('name'=>'THAILAND','code'=>'66'),
  'TL'=>array('name'=>'TIMOR-LESTE','code'=>'670'),
  'TG'=>array('name'=>'TOGO','code'=>'228'),
  'TO'=>array('name'=>'TONGA','code'=>'676'),
  'TK'=>array('name'=>'TOKELAU','code'=>'690'),
  'TT'=>array('name'=>'TRINIDAD AND TOBAGO','code'=>'1868'),
  'TN'=>array('name'=>'TUNISIA','code'=>'216'),
  'TR'=>array('name'=>'TURKEY','code'=>'90'),
  'TM'=>array('name'=>'TURKMENISTAN','code'=>'993'),
  'TC'=>array('name'=>'TURKS AND CAICOS ISLANDS','code'=>'1649'),
  'TV'=>array('name'=>'TUVALU','code'=>'688'),
  'UG'=>array('name'=>'UGANDA','code'=>'256'),
  'UA'=>array('name'=>'UKRAINE','code'=>'380'),
  'AE'=>array('name'=>'UNITED ARAB EMIRATES','code'=>'971'),
  'GB'=>array('name'=>'UNITED KINGDOM','code'=>'44'),
  'US'=>array('name'=>'UNITED STATES','code'=>'1'),
  'UY'=>array('name'=>'URUGUAY','code'=>'598'),
  'UZ'=>array('name'=>'UZBEKISTAN','code'=>'998'),
  'VU'=>array('name'=>'VANUATU','code'=>'678'),
  'VE'=>array('name'=>'VENEZUELA','code'=>'58'),
  'VN'=>array('name'=>'VIETNAM','code'=>'84'),
  'VG'=>array('name'=>'VIRGIN ISLANDS, BRITISH','code'=>'1284'),
  'VI'=>array('name'=>'VIRGIN ISLANDS, U.S.','code'=>'1340'),
  'YE'=>array('name'=>'YEMEN','code'=>'967'),
  'WF'=>array('name'=>'WALLIS AND FUTUNA','code'=>'681'),
  'ZM'=>array('name'=>'ZAMBIA','code'=>'260'),
  'ZW'=>array('name'=>'ZIMBABWE','code'=>'263')
);
